### ISSUE TITLE
[bug] lastfm cant load after new update.

### ISSUE THREAD

**Issue by kpopdev** [kennnyshiwa/kennnyshiwa-cogs#43]
[2021-04-12 16:13:24] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 171, in _load
    await bot.load_extension(spec)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/bot.py", line 1355, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/lastfm/__init__.py", line 1, in <module>
    from .lastfm import LastFM
  File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/lastfm/lastfm.py", line 217
    async def _api_request(
    ^
IndentationError: expected an indented block

**Comment by tigattack** [comment]
This will be fixed once #42 is merged.
